#!/bin/bash
rm -rf $HOME/instalarold
cd
if [ $(id -u) != 0 ]
then
echo "Ejecte este script como root"
exit
fi
echo -e "\033[0;34m ===================================\033[0m"
echo -e "\033[1;30m INSTALANDO VPSPACK-SERVER V2.0!\033[0m"
echo -e "\033[0;34m ===================================\033[0m"
echo -e "\033[1;33m Aguarde...\033[1;32m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null

wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/VPSPACK-SERVER-V2.0/master/vpspack.tgz > /dev/null 2>&1
tar xvfz /root/vpspack.tgz > /dev/null 2>&1
rm -rf /root/vpspack.tgz > /dev/null 2>&1
cp -a /root/vpspack/. /bin/ > /dev/null 2>&1
rm -rf /root/vpspack > /dev/null 2>&1
chmod +x /bin/limite
chmod +x /bin/criarusuario
chmod +x /bin/deletarusuario
chmod +x /bin/redefinirusuario
chmod +x /bin/vps
chmod +x /bin/speedtest.py

clear
echo -e "\033[0;34m =============================================================\033[0m"
echo -e "\033[1;30m VPSPACK-SERVER V2.0!\033[0m"
echo -e "\033[0;34m =============================================================\033[0m"
echo -e "\033[1;32m Instalacion concluida\n\033[1;30m Execute vps:"
echo -e "\033[0;34m =============================================================\033[0m"
echo -e "\033[1;31m • \033[1;37mvps\033[1;36m Menu de Opciones de Administracion\033[01;37m"
echo -e "\033[1;31m • \033[1;37mcriarusuario\033[1;33m Crear Usuario Con Fecha y limite de conexion\033[01;37m"
echo -e "\033[1;31m • \033[1;37mdeletarusuario\033[1;33m Eliminar usuario o solo desconectar\033[01;37m"
echo -e "\033[1;31m • \033[1;37mredefinirusuario\033[1;33m Editar un usuario\033[01;37m"
echo -e "\033[1;31m • \033[1;37mlimite\033[1;33m Limite de conexiones simultaneas\033[01;37m"
echo -e "\033[0;34m =============================================================\033[0m"
rm -rf $HOME/instalarold
